<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_System" Id="{5b40ff5c-73f8-4fe6-a7ad-41d6ddec4ec6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_System
VAR_INPUT
	bStart		: BOOL;
END_VAR
VAR_OUTPUT
	bError		: BOOL;
	bReady		: BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_Method" Id="{d9734ecd-488f-4054-b895-0e427b8dd8ba}">
      <Declaration><![CDATA[METHOD M_Method : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_System">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_System.M_Method">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>